hide_download: true
hide_download_original: null
leftnav:
- identifier: 80251cd0-ba9c-6032-7b2c-44a364c48796
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6e99538c-934a-efc8-14c9-05a834a52551
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 37212727-2cf7-b919-4a4c-397952899b9c
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1897761e-78d3-59dc-f5fe-323459810593
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: d3b07c27-e5d4-8d13-b9ff-06afa6ce12b9
  name: Lab Notes
  pageRef: /pages/lab-notes/
  weight: 50
- identifier: 692eb8f4-4606-291b-6612-d3c2ca17380a
  name: Microscope Conversions
  pageRef: /pages/lab-notes/microscope-conversions
  parent: d3b07c27-e5d4-8d13-b9ff-06afa6ce12b9
  weight: 60
